[CRM][DASH] Extend CrmOrch to support DASH resources.
oleksandrivantsiv/sonic-swss pull request #4
Opened 2023-04-07 10:00 UTC by oleksandrivantsiv

**What I did**
Extend CrmOrch to support DASH resources.

**Why I did it**
Add a possibility to monitor and report DASH critical resources.

**How I verified it**
Run VS tests.
A new `tests/test_crm_dash.py` is added to cover DASH CRM functionality.
**Details if related**

2023-04-10 23:05 UTC, dgsudharsan requested changes

2023-04-10 23:05 UTC, dgsudharsan commented on orchagent/crmorch.cpp
> +void CrmOrch::incCrmDashAclGroupUsedCounter(CrmResourceType resource, sai_object_id_t tableId)
Since we are using the same API for update rule and group Crm, can we rename the API to incCrmDashAclUsedCounter?

2023-04-10 23:05 UTC, dgsudharsan commented on tests/test_crm_dash.py
> +        entry.check_treshold_cleared()
Can we ensure all the configurations introduced as part of this test are cleaned up at the end?

2023-04-11 16:08 UTC, oleksandrivantsiv commented on orchagent/crmorch.cpp
> +void CrmOrch::incCrmDashAclGroupUsedCounter(CrmResourceType resource, sai_object_id_t tableId)
@dgsudharsan done

2023-04-11 23:33 UTC, dgsudharsan approved these changes

2023-04-18 11:50 UTC, closed without merging